## 1. Import PyTorch and Check Version

Let's start by importing PyTorch and checking that it's installed correctly.

In [1]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")
print(f"NumPy version: {np.__version__}")

PyTorch version: 2.9.1
NumPy version: 2.4.0


## 2. Creating Tensors

Tensors are the fundamental building blocks in PyTorch. They're similar to NumPy arrays but can run on GPUs for faster computation.

In [2]:
# Create a tensor from a list
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print("1D Tensor:")
print(tensor_1d)
print(f"Shape: {tensor_1d.shape}")
print(f"Data type: {tensor_1d.dtype}")

1D Tensor:
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Data type: torch.int64


In [3]:
# Create a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
print("2D Tensor (Matrix):")
print(tensor_2d)
print(f"Shape: {tensor_2d.shape}")

2D Tensor (Matrix):
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])


In [4]:
# Create tensors with specific values
zeros = torch.zeros(3, 3)  # 3x3 tensor of zeros
ones = torch.ones(2, 4)     # 2x4 tensor of ones
random = torch.rand(2, 3)   # 2x3 tensor with random values [0, 1)

print("Zeros:")
print(zeros)
print("\nOnes:")
print(ones)
print("\nRandom:")
print(random)

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Random:
tensor([[0.7110, 0.5264, 0.8935],
        [0.0250, 0.2099, 0.1420]])


## 3. Basic Tensor Operations

Let's perform some basic mathematical operations with tensors.

In [5]:
# Create two tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])

# Element-wise operations
print("a:", a)
print("b:", b)
print("\nAddition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)

a: tensor([1, 2, 3, 4])
b: tensor([5, 6, 7, 8])

Addition (a + b): tensor([ 6,  8, 10, 12])
Subtraction (a - b): tensor([-4, -4, -4, -4])
Multiplication (a * b): tensor([ 5, 12, 21, 32])
Division (a / b): tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [6]:
# Matrix multiplication
matrix_a = torch.tensor([[1, 2],
                         [3, 4]])
matrix_b = torch.tensor([[5, 6],
                         [7, 8]])

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nMatrix Multiplication (A @ B):")
print(matrix_a @ matrix_b)

Matrix A:
tensor([[1, 2],
        [3, 4]])

Matrix B:
tensor([[5, 6],
        [7, 8]])

Matrix Multiplication (A @ B):
tensor([[19, 22],
        [43, 50]])


## 4. Reshaping Tensors

Reshaping is crucial in neural networks where you need to transform data between different dimensions.

In [7]:
# Create a 1D tensor with 12 elements
tensor = torch.arange(12)
print("Original tensor:")
print(tensor)
print(f"Shape: {tensor.shape}")

# Reshape to 3x4
reshaped = tensor.view(3, 4)
print("\nReshaped to 3x4:")
print(reshaped)
print(f"Shape: {reshaped.shape}")

# Reshape to 2x6
reshaped2 = tensor.view(2, 6)
print("\nReshaped to 2x6:")
print(reshaped2)
print(f"Shape: {reshaped2.shape}")

Original tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Reshaped to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])

Reshaped to 2x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Shape: torch.Size([2, 6])


## 5. PyTorch Tensors vs NumPy Arrays

PyTorch tensors and NumPy arrays can be easily converted between each other.

In [8]:
# NumPy array to PyTorch tensor
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = torch.from_numpy(numpy_array)

print("NumPy array:")
print(numpy_array)
print(f"Type: {type(numpy_array)}")

print("\nPyTorch tensor:")
print(tensor_from_numpy)
print(f"Type: {type(tensor_from_numpy)}")

NumPy array:
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>

PyTorch tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: <class 'torch.Tensor'>


In [9]:
# PyTorch tensor to NumPy array
torch_tensor = torch.tensor([[7, 8, 9], [10, 11, 12]])
numpy_from_tensor = torch_tensor.numpy()

print("PyTorch tensor:")
print(torch_tensor)
print(f"Type: {type(torch_tensor)}")

print("\nNumPy array:")
print(numpy_from_tensor)
print(f"Type: {type(numpy_from_tensor)}")

PyTorch tensor:
tensor([[ 7,  8,  9],
        [10, 11, 12]])
Type: <class 'torch.Tensor'>

NumPy array:
[[ 7  8  9]
 [10 11 12]]
Type: <class 'numpy.ndarray'>


## 6. Check for GPU Availability

PyTorch can use GPUs for faster computation. Let's check if a GPU is available.

In [10]:
# Check if CUDA (NVIDIA GPU) is available
print(f"CUDA available: {torch.cuda.is_available()}")

# Check if MPS (Apple Silicon GPU) is available
print(f"MPS available: {torch.backends.mps.is_available()}")

# Determine the best device to use
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Using device: {device} ({torch.cuda.get_device_name(0)})")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print(f"Using device: {device} (Apple Silicon GPU)")
else:
    device = torch.device("cpu")
    print(f"Using device: {device}")

# Note: For this tutorial, CPU is perfectly fine!
# MNIST is a small dataset and trains quickly even on CPU

CUDA available: False
MPS available: True
Using device: mps (Apple Silicon GPU)


In [11]:
# Move a tensor to the device (CPU or GPU)
tensor_cpu = torch.tensor([1, 2, 3, 4, 5])
print(f"Tensor on: {tensor_cpu.device}")

# Move to the selected device
tensor_on_device = tensor_cpu.to(device)
print(f"Tensor moved to: {tensor_on_device.device}")

Tensor on: cpu
Tensor moved to: mps:0


## 7. Summary

Congratulations! You've completed Exercise 1. You now know:

✅ How to create tensors in PyTorch

✅ How to perform basic tensor operations

✅ How to reshape tensors

✅ How to convert between PyTorch tensors and NumPy arrays

✅ How to check for GPU availability and move tensors to different devices

### Next Steps

In Exercise 2, we'll load the MNIST dataset and prepare it for training!